MyStore/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyStore.Data;
using MyStore.Models;
using Microsoft.AspNetCore.Identity;


namespace MyStore.Controllers
{
    public class CustomersController : Controller
    {
        private readonly MyStoreContext _context;

        public CustomersController(MyStoreContext context)
        {

            _context = context;
        }

        [Authorize(Roles = SystemFunctions.ManageCustomer)]
        // GET: Customers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Customer.ToListAsync());
        }

        //[Authorize(Roles = SystemFunctions.ManageCustomer)]
        // GET: Customers/Details/5
        public async Task<IActionResult> Details(string phone)
        {
            string gettedNum = User.Claims.FirstOrDefault(i => i.Type == "CustomerPhone").Value;
            if (phone == null)
            {
                return NotFound();
            }


            var customer = await _context.Customer
                                .FirstOrDefaultAsync(m => m.CustomerPhone == phone);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Customer customer)
        {
            if (ModelState.IsValid)
            {

                _context.Add(customer);

                await _context.SaveChangesAsync();
                var customerId = customer.Id;
                return RedirectToAction(nameof(CongraCreated), new { id = customerId });
            }
            return View();
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id, string phone)
        {
            string gettedNum = User.Claims.FirstOrDefault(i => i.Type == "CustomerPhone").Value;

            if (id == null)
            {
                return NotFound();
            }

            if (User.IsInRole("Manage_Customer"))
            {
                var customer = await _context.Customer.FirstOrDefaultAsync(m => m.Id == id);
                if (customer == null)
                {
                    return NotFound();
                }
                return View(customer);
            }


            else if(phone == gettedNum)
            {
                var customer = await _context.Customer.FirstOrDefaultAsync(m => m.Id == id);
                if (customer == null)
                {
                    return NotFound();
                }
                return View(customer);
            }

            return NotFound();

        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Customer customer)
        {
            string gettedNum = User.Claims.FirstOrDefault(i => i.Type == "CustomerPhone").Value;
            if (id != customer.Id)
            {
                return NotFound();
            }

            if (User.IsInRole("Manage_Customer"))
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(customer);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!CustomerExists(customer.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
            }
            else
            {

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(customer);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!CustomerExists(customer.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Details), new { id = id, phone = gettedNum });

                }

            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            string gettedNum = User.Claims.FirstOrDefault(i => i.Type == "CustomerPhone").Value;
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer.FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);

        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.Customer.FindAsync(id);
            _context.Customer.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(int id)
        {
            return _context.Customer.Any(e => e.Id == id);
        }

        public IActionResult CongraCreated(int Id)
        {
            ViewBag.ID = Id;
            return View();
        }

        public IActionResult CustomerLogin(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> CustomerLogin(CustomerLoginModel model, string returnUrl)
        {
            var validUser = await _context.Customer.FirstOrDefaultAsync(i => i.CustomerPhone == model.CustomerPhoneNumber);
            if (validUser == null)
            {
                ModelState.AddModelError(string.Empty, "Số điện thoại chưa đăng ký hoặc nhập sai số điện thoại xin vui lòng thử lại hoặc đăng ký số điện thoại");
            }
            if (ModelState.IsValid)
            {
                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                identity.AddClaim(new Claim(ClaimTypes.Name, validUser.CustomerName));
                identity.AddClaim(new Claim(ClaimTypes.MobilePhone, model.CustomerPhoneNumber));
                identity.AddClaim(new Claim(CustomClaim.Fullname, validUser.CustomerName));
                identity.AddClaim(new Claim(CustomClaim.Address, validUser.ShippingAddress));
                identity.AddClaim(new Claim("CustomerPhone", model.CustomerPhoneNumber));

                var principal = new ClaimsPrincipal(identity);

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                if (!string.IsNullOrWhiteSpace(returnUrl) && Url.IsLocalUrl(returnUrl))
                {
                    return Redirect(returnUrl);
                }

                return RedirectToAction("Index", "Home");
            }

            return View();
        }
    }
}

MyStore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MyStore.Data;
using MyStore.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MyStore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly MyStoreContext _context;

        public HomeController(MyStoreContext context, ILogger<HomeController> logger)
        {
            _context = context;
            _context.Controller = this;
            _logger = logger;
        }

        
        public async Task<IActionResult> Index(string keyWord)
        {

            if (string.IsNullOrWhiteSpace(keyWord))
            {
                ////check user already provide phonenumber
                //var shoppingCart = new ShoppingCart();
                //shoppingCart.OrderHeader = new OrderHeader();
                //shoppingCart.OrderDetails = await _context.Product.Select(i => new OrderDetail()
                //{
                //    ProductId = i.Id,
                //    Price = i.Price,
                //    BonusPercentage = i.BonusPercentage
                //}).ToListAsync();

                var listProduct = new ShoppingCart();
                listProduct.OrderHeader = new OrderHeader();
                listProduct.OrderDetails = new List<OrderDetail>();
                listProduct.Products = await _context.Product.ToListAsync();

                return View(listProduct);
            }
            else
            {
                var listProduct = new ShoppingCart();
                listProduct.OrderHeader = new OrderHeader();
                listProduct.OrderDetails = new List<OrderDetail>();
                listProduct.Products = await _context.Product.Where(m => (m.Name ?? "").Contains(keyWord)).ToListAsync();
                ViewBag.KeyWord = keyWord;

                return View(listProduct);
            }

         }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyStore/Views/Home/Index.cshtml
@model ShoppingCart
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">FRESH FRUITS</h1>
    <p>WELCOME EVERYBODY TO MY FRESH FRUITS SHOP</a>.</p>
</div>
<form asp-controller="Home" asp-action="Index">
    <span>Search By Name</span>
    <input type="text" name="keyWord" value="@ViewBag.KeyWord" />
    <button class="btn btn-info">Search</button>
</form>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Products[0].Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Products[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Products[0].Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Products[0].BonusPercentage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Products[0].RemainingStock)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Products)
        {
            @if (User.Identity.IsAuthenticated)
            {
                <tr onclick="location.href ='@Url.Action("Create", "OrderDetails", new { id=item.Id ,
                                                                                 name=item.Name,
                                                                                 price=item.Price,
                                                                                 bonuspercent=item.BonusPercentage})'">
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BonusPercentage)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RemainingStock)
                    </td>
                </tr>

            }
            else
            {
                <tr onclick="location.href ='@Url.Action("CustomerLogin", "Customers")'">
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BonusPercentage)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RemainingStock)
                    </td>
                </tr>
            }

        }
    </tbody>
</table>