MyStore/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyStore.Data;
using MyStore.Models;

namespace MyStore.Controllers
{
    [Authorize(Roles = SystemFunctions.ManageAccount)]
    public class AccountsController : Controller
    {
        private readonly MyStoreContext _context;

        public AccountsController(MyStoreContext context)
        {
            _context = context;
        }

        // GET: Accounts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Account.ToListAsync());
        }

        // GET: Accounts/Details/5
        public async Task<IActionResult> Details(string id )
        {
            if (id == null)
            {
                return NotFound();

            }

            var account = await _context.Account
                .FirstOrDefaultAsync(m => m.Username == id);
            if (account == null)
            {
                return NotFound();
            }
            return View(account);
        }

        // GET: Accounts/Create
        public async Task<IActionResult> Create()
        {
            var Rolecodelist = await _context.RoleMaster
                .AsNoTracking()
                .Select(x => new { x.RoleCode, x.RoleName }).ToListAsync();
            var takerolecodelist = new SelectList(Rolecodelist, "RoleCode", "RoleCode");
            ViewData["RoleCode"] = takerolecodelist;
            return View();
        }

        // POST: Accounts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Username,Password,Fullname,EmailAdress,PhoneNumber,RoleCode")] Account account)
        {

            if (ModelState.IsValid)
            {
                _context.Add(account);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            var Rolecodelist = await _context.RoleMaster
                    .AsNoTracking()
                    .Select(x => new { x.RoleCode, x.RoleName }).ToListAsync();
            var takerolecodelist = new SelectList(Rolecodelist, "RoleCode", "RoleCode");
            ViewData["RoleCode"] = takerolecodelist;

            return View(account);
        }

        // GET: Accounts/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Account.FindAsync(id);
            if (account == null)
            {
                return NotFound();
            }
            var Rolecodelist = await _context.RoleMaster
                .AsNoTracking()
                .Select(x => new { x.RoleCode, x.RoleName }).ToListAsync();
            var takerolecodelist = new SelectList(Rolecodelist, "RoleCode", "RoleCode");
            ViewData["RoleCode"] = takerolecodelist;
            return View(account);
        }

        // POST: Accounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Username,Password,Fullname,EmailAdress,PhoneNumber,RoleCode")] Account account)
        {
            if (id != account.Username)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(account);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AccountExists(account.Username))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            var Rolecodelist = await _context.RoleMaster
                .AsNoTracking()
                .Select(x => new { x.RoleCode, x.RoleName }).ToListAsync();
            var takerolecodelist = new SelectList(Rolecodelist, "RoleCode", "RoleCode");
            ViewData["RoleCode"] = takerolecodelist;


            return View(account);
        }

        // GET: Accounts/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var account = await _context.Account
                .FirstOrDefaultAsync(m => m.Username == id);
            if (account == null)
            {
                return NotFound();
            }

            return View(account);
        }

        // POST: Accounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var account = await _context.Account.FindAsync(id);
            _context.Account.Remove(account);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AccountExists(string id)
        {
            return _context.Account.Any(e => e.Username == id);
        }
    }
}

MyStore/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyStore.Data;
using MyStore.Models;

namespace MyStore.Controllers
{
    [Authorize(Roles = SystemFunctions.ManageProduct)]
    public class ProductsController : Controller
    {
        private readonly MyStoreContext _context;

        public ProductsController(MyStoreContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await _context.Product.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price,BonusPercentage,RemainingStock,CreatedBy,CreatedTime,UpdatedBy,UpdatedTime")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Product.FindAsync(id);
            _context.Product.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Product.Any(e => e.Id == id);
        }

        public async Task<IActionResult> ConfirmItem(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var listItem = await _context.Product.FirstOrDefaultAsync(m => m.Id == id);

            if(listItem == null)
            {
                return NotFound();
            }

            return View(listItem);
        }

    }
}

MyStore/Controllers/RoleMastersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyStore.Data;
using MyStore.Models;

namespace MyStore.Controllers
{
    [Authorize(Roles = SystemFunctions.ManageRoleMaster)]
    public class RoleMastersController : Controller
    {
        private readonly MyStoreContext _context;

        public RoleMastersController(MyStoreContext context)
        {
            _context = context;
        }

        // GET: RoleMasters
        public async Task<IActionResult> Index()
        {
            return View(await _context.RoleMaster.ToListAsync());
        }

        // GET: RoleMasters/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roleMaster = await _context.RoleMaster
                .FirstOrDefaultAsync(m => m.RoleCode == id);
            if (roleMaster == null)
            {
                return NotFound();
            }

            return View(roleMaster);
        }

        // GET: RoleMasters/Create
        public IActionResult Create()
        {

            return View();
        }

        // POST: RoleMasters/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RoleCode,RoleName")] RoleMaster roleMaster)
        {
            if (ModelState.IsValid)
            {
                _context.Add(roleMaster);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(roleMaster);
        }

        // GET: RoleMasters/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roleMaster = await _context.RoleMaster.FindAsync(id);
            if (roleMaster == null)
            {
                return NotFound();
            }
            return View(roleMaster);
        }

        // POST: RoleMasters/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("RoleCode,RoleName")] RoleMaster roleMaster)
        {
            if (id != roleMaster.RoleCode)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(roleMaster);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleMasterExists(roleMaster.RoleCode))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(roleMaster);
        }

        // GET: RoleMasters/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roleMaster = await _context.RoleMaster
                .FirstOrDefaultAsync(m => m.RoleCode == id);
            if (roleMaster == null)
            {
                return NotFound();
            }

            return View(roleMaster);
        }

        // POST: RoleMasters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var roleMaster = await _context.RoleMaster.FindAsync(id);
            _context.RoleMaster.Remove(roleMaster);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoleMasterExists(string id)
        {
            return _context.RoleMaster.Any(e => e.RoleCode == id);
        }
    }
}

MyStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Manage_Product"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                                </li>
                            }

                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="OrderDetails" asp-action="Index">Order Details</a>
                            </li>
                        }


                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Manage_Account"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Index">Account</a>
                                </li>
                            }

                        }

                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Manage_Customer"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                                </li>
                            }

                        }

                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Manage_Role_Master"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="RoleMasters" asp-action="Index">Role Masters</a>
                                </li>
                            }

                        }

                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Manage_Role_Permision"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="RolePermisions" asp-action="Index">Role Permision</a>
                                </li>
                            }

                        }

                    </ul>
                    <ul class="nav justify-content-end">

                        @if (User.Identity.IsAuthenticated)
                        {

                            <li class="nav-item">
                                <a asp-action="Details" asp-controller="Customers" asp-route-phone="@User.Claims.FirstOrDefault(i => i.Type == "CustomerPhone").Value" class="nav-link">
                                    Xin Chào @User.Claims.FirstOrDefault(i => i.Type == CustomClaim.Fullname).Value
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" asp-controller="Authentication" asp-action="Logout">Log Out</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link active" asp-controller="Customers" asp-action="Create">Custome Registor</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" asp-controller="Customers" asp-action="CustomerLogin">Log In</a>
                            </li>
                        }

                    </ul>
                </div>


            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MyStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>